--enable-wayland-ime
--ozone-platform=wayland
--wayland-per-window-scaling
--wayland-text-input-version=3
--enable-features=AcceleratedVideoDecodeLinuxZeroCopyGL,AcceleratedVideoDecodeLinuxGL,VaapiIgnoreDriverChecks,VaapiOnNvidiaGPUs
