[bar.default]

[shell]
polkit_agent = true

[shell.screenshot]
save_to_file = true
directory = "~/Pictures/screenshots"
copy_to_clipboard = true

# 外接显示器（无 /sys/class/backlight）走 DDC/CI 控制亮度；配合 ~/.config/ddcutil/ddcutilrc 的 --use-file-io
[brightness]
enable_ddcutil = true

[widget.clock]
format = "{:%a %m-%d %H:%M}"  # 周六 08-01 10:45（带星期）

[control_center]
hidden_tabs = [ "power" ]

    [control_center.calendar]
    show_events_card = false

[desktop_widgets]
schema_version = 2
widget_order = []

    [desktop_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [desktop_widgets.widget]

[dock]
enabled = true
icon_size = 32
pinned = [ "firefox", "kitty", "dolphin" ]

[location]
address = "shanghai,china"

[lockscreen]
fingerprint = false

[lockscreen_widgets]
enabled = false
schema_version = 2
widget_order = [ "lockscreen-login-box@HDMI-A-1" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1"]
    box_height = 196.0
    box_width = 810.0
    cx = 1152.0
    cy = 1114.0
    output = "HDMI-A-1"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

[theme]
builtin = "Eldritch"
community_palette = "Oxocarbon"
mode = "dark"
source = "wallpaper"
wallpaper_scheme = "m3-content"

[wallpaper]
directory = "/home/wahoya/Pictures/wallpapers"
directory_dark = "/home/wahoya/Pictures/wallpapers/lock"
directory_light = "/home/wahoya/Pictures/wallpapers"

    [wallpaper.default]
    path = "/usr/share/noctalia/assets/noctalia-wallpaper.png"

    [wallpaper.last]
    path = "/home/wahoya/Pictures/wallpapers/Dome sweet dome-Adam Burton-Alamy.jpg"

    [wallpaper.monitors.HDMI-A-1]
    path = "/home/wahoya/Pictures/wallpapers/Dome sweet dome-Adam Burton-Alamy.jpg"
